---
version: '3'

networks:
  public: {}
  privilege: {}

volumes:
  pushgateway: {}
  consul-data: {}
  consul-conf: {}

services:
  prometheus-pusher:
    image: atompi/prometheus-pusher:v1.0.0
    container_name: prometheus-pusher
    hostname: prometheus-pusher100
    restart: always
    environment:
      PUSH_GATEWAY: http://pushgateway:9091
      PORT: 9191
      GIN_MODE: "release"
    volumes:
    - /usr/local/prometheus-pusher/prometheus.yml:/prometheus.yml
    - /etc/hosts:/etc/hosts
    entrypoint:
    - /prometheus_pusher
    - -config.file
    - /prometheus.yml
    networks:
    - privilege
    depends_on:
    - consul

  pushgateway:
    image: prom/pushgateway:v0.5.2
    container_name: pushgateway
    hostname: pushgateway052
    restart: always
    volumes:
    - pushgateway:/pushgateway
    networks:
    - privilege
    depends_on:
    - consul

  consul:
    image: consul:1.2.2
    container_name: consul
    hostname: consul122
    command: agent -server -client=0.0.0.0 -ui -bootstrap-expect 1
    restart: always
    volumes:
    - consul-data:/consul/data
    - consul-conf:/consul/config
    - /etc/hosts:/etc/hosts
    networks:
    - privilege

  monitor-node:
    image: prom/node-exporter:v0.15.2
    container_name: node_exporter
    hostname: monitor-node
    restart: always
    pid: "host"
    networks:
    - privilege

  nginx:
    image: nginx:1.14.0
    container_name: nginx
    hostname: nginx1140
    restart: always
    ports:
    - "9091:9091"
    - "9191:9191"
    - "8500:8500"
    volumes:
    - /data/nginx/conf/stream.d:/etc/nginx/stream.d
    - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /data/nginx/logs:/var/log/nginx
    networks:
    - public
    - privilege
    depends_on:
    - pushgateway